### ISSUE TITLE
Dificuldade com Matrizes

### ISSUE THREAD

**Issue by JayCesar** [JayCesar/java-springboot#15]
Eu encontrei dificuldade com matrizes na parte que envolve buscar itens nas posições dentro dela

**Exercício:**
Fazer um programa para ler dois números inteiros M e N, e depois ler uma matriz de M linhas por N colunas contendo números inteiros, podendo haver repetições. Em seguida, ler um número inteiro X que pertence à matriz. Para cada ocorrência de X, mostrar os valores à esquerda, acima, à direita e abaixo de X, quando houver, conforme exemplo

**Exemplo**
![2023-04-22_08h56_42](https://user-images.githubusercontent.com/44206400/233783303-8a7798dd-419b-476b-98d9-aa1a1ffa5e9a.png)

**Código:**
```
package classes;

import java.util.Locale;
import java.util.Scanner;

public class MatrizExercise {

	public static void main(String[] args) {
		Locale.setDefault(Locale.US);
		Scanner sc = new Scanner(System.in);
		
		int M = sc.nextInt();
		int N = sc.nextInt();
		
		int[][] mat = new int[M][N];
		
		for (int i = 0; i < mat.length; i++) {
			for (int j = 0; j < mat[i].length; j ++) {
				mat[i][j] = sc.nextInt();
			}
		}
		
		int X = sc.nextInt();
		
		for (int i = 0; i < mat.length; i++) {
			for (int j = 0; j < mat[i].length; j++) {
				if (mat[i][j] == X) {
					System.out.print("Position: " + i + ", " + j + ": \n");
					if (j > 0) {
						System.out.println("Left: " + mat[i][j-1]);
					}	
					if (i > 0) {
						System.out.println("Up: " + mat[i - 1][j]);
					}
					if (j < mat[i].length-1) {
						System.out.println("Right: " + mat[i][j+1]);
					}
					if (i < mat.length-1) {
						System.out.println("Down: " + mat[i+1][j]);
					}
					
				}
			}
		}
		
	
		sc.close();

	}



}

```

**Comment by salvedojuliao** [comment]
**PDF:**
[05-memoria-arrays-e-listas (1).pdf](https://github.com/salvedojuliao/course-java-POO/files/11301333/05-memoria-arrays-e-listas.1.pdf)
