### ISSUE TITLE
Principais IDEs para Java e Spring (Week DevSuperior)

### ISSUE THREAD

**Issue by JayCesar** [JayCesar/java-springboot#20]
### Para desenolver aplicativos comerciais em qualquer linguagem:

Eu tenho que **instalar**:

**SDK (Software Development Kit) da linguagem:**
- Compliador / Interpretador
- Bibliotecas padrão
- Ferramentas padrão da linguagem;

**Framework de linguagem**
 - Para eu produzir de forma ma**is produtiva

IDE
- Ambiente de desenvolvimento;
____________

![2023-04-27_10h30_33](https://user-images.githubusercontent.com/44206400/234877338-d98c2aa1-cb52-4acb-a1cd-27e53eb62dec.png)

- O JDK é distribuido de forma gratuita por empresas como a **Azul Zulu, Adopt, Amazon Corretto** mas a **Oracle** é paga!
-O Spring Boot é utilizado para desenvolver com Java

___________

### IDE's

![2023-04-27_10h33_08](https://user-images.githubusercontent.com/44206400/234878054-ae6dc753-8b35-450b-9c8c-d799f280ca3e.png)

O "pessoal" da Spring criam plugins chamados "Spring Tools" que pode ser utilizados com o VS Code, Eclipse e Theia

Theia é um **Mix do Vs Code** com o Eclipse!

**Comment by salvedojuliao** [comment]
**Etapas do Spring (Instalação)**
1) Eu preciso acessar o Sprinng Initializr,
2) Baixar o arquivo (após adicioanr as configurações desejadas)
3) Extrair o arquivo dentro da pasta de projetos que coloquei como princial do STS (Springboot Tools)
4) Abrir essa pasta - utilizando o Maven - ou outro gerenciador que selecionei antes de baixar no Spring Initiazr
5) Testar par averificar se está funcionando


Maven é o gerenciador de dependências que pode ser utilizado no spring!
