### ISSUE TITLE
API Rest Java e Spring - Exemplo na prática (Week DevSuperior)

### ISSUE THREAD

**Issue by JayCesar** [JayCesar/java-springboot#22]
## O que precisamos fazer para criar uma aplicação web que disponibiliza uma API Rest?

1) Primeiro a gente precisa de um **Web Server** (É uma aplicação que recebe nossa aplicação Java + Spring) e será ele que irá escutar as requisições e responder à elas!

2) Nossa aplicação será a **App Srping Boot Java**. 
- Ela é uma aplicação **Multi-threading**, ou seja, a cada requisição ela abre um processo em execução que vai processar a execução e depois retorna a resposta.
- Mapeamento de URL - ou seja, buscar os dados a partir da URL - processar os dados obtidos a partir da URL
- Serialização JSON - transformar os objetos em Java em JSON!

**Conclusão:** Ou seja, fazer tudo isso utilizando apenas uma linguagem do zero levaria muito tempo e um trabalho muito complexo. Por isso para agilizar o processo nós utilizamos um framework e é aqui que entra o **Spring**.

O **Spring** é um framework Java criado com o objetivo de facilitar o desenvolvimento de aplicações, explorando, para isso, os conceitos de Inversão de Controle e Injeção de Dependências.

![2023-05-02_16h59_13](https://user-images.githubusercontent.com/44206400/235772626-21f187f2-27de-4b5b-988c-0bfb0222dea6.png)

**Comment by salvedojuliao** [comment]
### Esse é o  modelo de domínio:
![2023-05-02_17h08_53](https://user-images.githubusercontent.com/44206400/235774614-f02654f0-5e2a-4685-b0b5-dbebf112457d.png)
