### ISSUE TITLE
Instalação do Docker (Java Week)

### ISSUE THREAD

**Issue by JayCesar** [JayCesar/java-springboot#41]
### Docker
É um sistema que permite criar containers
Container é como se fosse uma MVM que compartilha o 'kerner' do windows da máquina local. 

**Dockers desktop:** https://www.docker.com/products/docker.desktop/

**Comment by salvedojuliao** [comment]
Link do git: 
https://github.com/devsuperior/wsl-win10

-------------

### WSL: Subsistema Windoes para Linux
**Subsistema Windoes para Linux** Ele permite rodar o linux no windows de forma integrada! Isso signfica que o Linux irá comparilhar coisas importantes com o Windows.

**Comment by salvedojuliao** [comment]
## Windows Terminal
Ele dá uma flexibilidade maior de trabalhar de forma itnegrada com o linux. Eu abro ele e aponto para o terminal do ubuntu.
