### ISSUE TITLE
Aula 1: Introdução + Projeto estruturado

### ISSUE THREAD

**Issue by JayCesar** [JayCesar/java-springboot#42]
### Destaque para o excesso de informação 
![2023-05-08_20h38_41](https://user-images.githubusercontent.com/44206400/236959531-4221633d-3abf-4309-8a6e-5cdf65c403a3.png)

### Método ERA
![2023-05-08_20h39_29](https://user-images.githubusercontent.com/44206400/236959587-7110a9e5-1a4b-4aad-b6a3-11d6944d3c6a.png)

## Por que Java Spring?
Sim, Java está entre as linguagens mais demandandas do mercado! Javascript é voltado para o Front-end! (e domina).
> Tip: https://facebook.com/jobs

**Comment by salvedojuliao** [comment]
## Sistemas web
![2023-05-08_20h47_41](https://user-images.githubusercontent.com/44206400/236960396-67d0f8d1-b42c-4e06-b975-ab0e0d3b7c22.png)

💡O front-end conversa com back-end por meio de requsições HTTP/JSON. Essa requisição estará no formato **Json**!

- O **H2** é um banco para testes
- O **Postgressql** é usado para aplicaçãona nuvem

**Comment by salvedojuliao** [comment]
## API Rest
💡**APTI** é só o que está exposto para a web
É como se a maçaneta fosse a API da porta! A maçaneta é só uma interface para você mexer com a porta. [votlar aqui]

**Comment by salvedojuliao** [comment]
## Padrão Camadas
É importante que a gente organiza os componentes/código em camadas, sendo cada uma responsável por algo específico. Isso facilita na organização e na manutenção futura.

![2023-05-08_21h09_02](https://user-images.githubusercontent.com/44206400/236962498-5b5ad61b-0913-4cb4-8270-2eab8e2092bf.png)

**Comment by salvedojuliao** [comment]
**ORM:** Mapemaneto Objeto Relacional
Para que o objeto game seja mapeado e vire um registro na tabela de games do banco relacional, é necessário fazer algumas configurações:

Configura a classe Java para que ela seja equivalente a uma tabela do banco relacional
![2023-05-08_21h58_40](https://user-images.githubusercontent.com/44206400/236967565-c2f92d49-8403-4120-a400-ca1dab4f6f11.png)

**Comment by salvedojuliao** [comment]
**Repository** é o objeto responsável por fazer consulta ao banco de dados

**Service** é o componente responsável por implementar a lógica de negócio!

**Controller** é a porta de entrar do backend - é ele que disponibiliza a API.

![2023-05-08_22h48_29](https://user-images.githubusercontent.com/44206400/236973521-9fd9207c-b861-4079-8604-c92f1e1a58e9.png)

**Comment by salvedojuliao** [comment]
**PDF:**
[aula1-intensivao-java-spring.pdf](https://github.com/salvedojuliao/course-java-POO/files/11426556/aula1-intensivao-java-spring.pdf)
