### ISSUE TITLE
Aula 2: Domínio, consultas

### ISSUE THREAD

**Issue by JayCesar** [JayCesar/java-springboot#43]
![2023-05-10_10h02_35](https://github.com/salvedojuliao/course-java-POO/assets/44206400/c4c2271d-f1f9-4092-96e6-5731f5683c67)

💡A classe ItemPedido é uma **classe de associação!** Isso ocorroe quando há uma relação de muitos para muitos com **dados adicionais**.

### No diagrama:
![2023-05-10_10h05_42](https://github.com/salvedojuliao/course-java-POO/assets/44206400/d39d0076-ce55-4608-9971-65776b9c0bda)

### Na memória:
![image](https://github.com/salvedojuliao/course-java-POO/assets/44206400/00c0413f-c170-4083-a981-0d6be82705ac)

### Banco de dados relacional (dados representados em foram de tabela):
![image](https://github.com/salvedojuliao/course-java-POO/assets/44206400/42b62d23-1578-4f18-9fa1-8dd5ddcc096e)

### O mesmo ocorre no projeto que está sendo desnvolvido, ou seja, há um 'item' no desenvolvimento ,ou seja, o 'belonging':
![image](https://github.com/salvedojuliao/course-java-POO/assets/44206400/b1e9d444-2ee0-4526-adf3-0ed31a5d01d8)

**Comment by salvedojuliao** [comment]
![2023-05-10_10h02_35](https://github.com/salvedojuliao/course-java-POO/assets/44206400/c4c2271d-f1f9-4092-96e6-5731f5683c67)

💡A classe ItemPedido é uma **classe de associação!** Isso ocorroe quando há uma relação de muitos para muitos com **dados adicionais**.

### No diagrama:
![2023-05-10_10h05_42](https://github.com/salvedojuliao/course-java-POO/assets/44206400/d39d0076-ce55-4608-9971-65776b9c0bda)

### Na memória:
![image](https://github.com/salvedojuliao/course-java-POO/assets/44206400/00c0413f-c170-4083-a981-0d6be82705ac)

### Banco de dados relacional (dados representados em foram de tabela):
![image](https://github.com/salvedojuliao/course-java-POO/assets/44206400/42b62d23-1578-4f18-9fa1-8dd5ddcc096e)


### O mesmo ocorre no projeto que está sendo desnvolvido, ou seja, há um 'item' no desenvolvimento ,ou seja, o 'belonging':
![image](https://github.com/salvedojuliao/course-java-POO/assets/44206400/b1e9d444-2ee0-4526-adf3-0ed31a5d01d8)

**Comment by salvedojuliao** [comment]
**<<pk>>** seria a 'primary Key'

**Comment by salvedojuliao** [comment]
É imporntate colocar anotações no service para que ele fique transcaionais

ASID: Atomica, consitentes, isolada e druavel

Ou seja, para que haja de fato uam conversa entre o banco de dados e as requisições!

**Comment by salvedojuliao** [comment]
PDF da aula:
[aula2-intensivao-java-spring.pdf](https://github.com/salvedojuliao/course-java-POO/files/11444421/aula2-intensivao-java-spring.pdf)
